name: QML CMake Linux Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'CMake 构建类型'
        required: true
        default: 'Release'
        type: choice
        options: [Release, Debug, RelWithDebInfo]

# 防抖：同一分支并发触发时取消旧任务，省分钟数
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# 最小权限
permissions:
  contents: read

env:
  CMAKE_GENERATOR: Ninja
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      # 先检查可用的Qt版本
      - name: Check available Qt versions
        run: |
          python3 -m pip install aqtinstall
          python3 -m aqt list-qt linux desktop

      # 使用稳定的Qt 6.5.3 LTS版本，移除aqt版本限制
      - name: Install Qt 6.5.3
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          # 移除aqtversion限制，让action使用默认版本
          # aqtversion: '==3.3.*'  # 注释掉这行
          modules: 'qtdeclarative qttools'  # 简化模块列表
          cache: true

      - name: Show Qt paths (debug)
        run: |
          echo "Qt6_DIR=$Qt6_DIR"
          echo "QT_ROOT_DIR=$QT_ROOT_DIR"
          ls -la "$Qt6_DIR" || echo "Qt6_DIR not found"
          ls -la "$QT_ROOT_DIR" || echo "QT_ROOT_DIR not found"

      - name: Configure (CMake)
        run: |
          cmake -S . -B build -G "${{ env.CMAKE_GENERATOR }}" \
            -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }} \
            -DCMAKE_PREFIX_PATH="${Qt6_DIR:-$QT_ROOT_DIR}"

      - name: Build
        run: cmake --build build -j

      # 如需跑测试且启用了 CTest，可打开
      # - name: Test
      #   run: |
      #     cd build
      #     ctest --output-on-failure

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ github.event.inputs.build_type }}
          path: build/**
          if-no-files-found: error
          retention-days: 3
